from sentence_transformers import SentenceTransformer
import faiss
import numpy as np


class FAISSRetriever:
    """
    Lightweight dense retriever using Sentence Transformers
    and FAISS.

    Pipeline:

        Document Chunks
              ↓
        Sentence Embeddings
              ↓
             FAISS
              ↓
        Query Embedding
              ↓
          Top-K Chunks
              ↓
       Chunk + Metadata
    """

    def __init__(
        self,
        model_name: str = "all-MiniLM-L6-v2"
    ):
        """
        Initialize the embedding model and FAISS index.

        Parameters
        ----------
        model_name : str
            Sentence Transformer model used for embeddings.
        """

        self.model_name = model_name

        print(
            f"Loading retrieval model: "
            f"{self.model_name}"
        )

        self.model = SentenceTransformer(
            self.model_name
        )

        # all-MiniLM-L6-v2 produces 384-dimensional
        # embeddings.
        self.embedding_dimension = (
            self.model.get_embedding_dimension()
        )

        # Normalized embeddings + inner product
        # gives cosine similarity.
        self.index = faiss.IndexFlatIP(
            self.embedding_dimension
        )

        # Metadata is stored separately because FAISS
        # stores vectors, not arbitrary Python objects.
        self.documents = []

        print(
            "Retrieval model loaded successfully."
        )

        print(
            f"Embedding dimension: "
            f"{self.embedding_dimension}"
        )

    def _embed(
        self,
        texts: list[str]
    ) -> np.ndarray:
        """
        Convert text into normalized embeddings.

        Parameters
        ----------
        texts : list[str]
            Texts to embed.

        Returns
        -------
        np.ndarray
            Normalized float32 embeddings.
        """

        if not texts:

            return np.empty(
                (
                    0,
                    self.embedding_dimension
                ),
                dtype=np.float32
            )

        embeddings = self.model.encode(
            texts,
            normalize_embeddings=True
        )

        return np.asarray(
            embeddings,
            dtype=np.float32
        )

    def add_chunks(
        self,
        chunks: list[dict]
    ) -> None:
        """
        Add metadata-aware chunks to the FAISS index.

        Each chunk should contain:

            text
            chunk_id
            document_id
            document_name
            chunk_index

        Parameters
        ----------
        chunks : list[dict]
            Chunk records generated by the ingestion/chunking
            pipeline.
        """

        if not chunks:

            raise ValueError(
                "Chunks cannot be empty."
            )

        valid_chunks = []

        for chunk in chunks:

            text = chunk.get(
                "text",
                ""
            )

            if not text or not text.strip():
                continue

            valid_chunks.append(
                {
                    "chunk_id": chunk.get(
                        "chunk_id"
                    ),
                    "document_id": chunk.get(
                        "document_id"
                    ),
                    "document_name": chunk.get(
                        "document_name"
                    ),
                    "chunk_index": chunk.get(
                        "chunk_index"
                    ),
                    "text": text.strip()
                }
            )

        if not valid_chunks:

            raise ValueError(
                "No valid chunks were provided."
            )

        texts = [
            chunk["text"]
            for chunk in valid_chunks
        ]

        embeddings = self._embed(
            texts
        )

        self.index.add(
            embeddings
        )

        self.documents.extend(
            valid_chunks
        )

    def add_documents(
        self,
        documents: list[str]
    ) -> None:
        """
        Backward-compatible method for adding plain text
        documents.

        Each text is converted into a basic metadata record.

        Parameters
        ----------
        documents : list[str]
            Text documents/chunks.
        """

        if not documents:

            raise ValueError(
                "Documents cannot be empty."
            )

        chunks = []

        for index, document in enumerate(
            documents
        ):

            if not document or not document.strip():
                continue

            chunks.append(
                {
                    "chunk_id": str(index),
                    "document_id": index,
                    "document_name": (
                        f"document_{index}"
                    ),
                    "chunk_index": index,
                    "text": document.strip()
                }
            )

        self.add_chunks(
            chunks
        )

    def search(
        self,
        query: str,
        top_k: int = 5
    ) -> list[dict]:
        """
        Retrieve the most relevant chunks.

        Parameters
        ----------
        query : str
            User query.

        top_k : int
            Number of chunks to retrieve.

        Returns
        -------
        list[dict]
            Retrieved chunks containing:

                text
                score
                rank
                chunk_id
                document_id
                document_name
                chunk_index
        """

        if not query or not query.strip():

            raise ValueError(
                "Query cannot be empty."
            )

        if self.index.ntotal == 0:

            raise RuntimeError(
                "No chunks have been indexed."
            )

        if top_k <= 0:

            raise ValueError(
                "top_k must be greater than zero."
            )

        top_k = min(
            top_k,
            self.index.ntotal
        )

        query_embedding = self._embed(
            [query]
        )

        scores, indices = self.index.search(
            query_embedding,
            top_k
        )

        results = []

        for rank, (
            score,
            index
        ) in enumerate(
            zip(
                scores[0],
                indices[0]
            ),
            start=1
        ):

            if index < 0:
                continue

            chunk = self.documents[
                index
            ]

            results.append(
                {
                    "text": chunk["text"],
                    "score": float(score),
                    "rank": rank,
                    "chunk_id": chunk[
                        "chunk_id"
                    ],
                    "document_id": chunk[
                        "document_id"
                    ],
                    "document_name": chunk[
                        "document_name"
                    ],
                    "chunk_index": chunk[
                        "chunk_index"
                    ]
                }
            )

        return results

    def clear(self) -> None:
        """
        Clear the FAISS index and metadata.
        """

        self.index.reset()

        self.documents = []

    @property
    def document_count(self) -> int:
        """
        Return the number of indexed chunks.
        """

        return len(
            self.documents
        )